version: '3'
services:
 nexus:
  image: sonatype/nexus3
  restart: always
  ports:
   - 8081:8081
   - 8083:8083  
  volumes:
   - nexus:/nexus-data
 jenkins:
  image: jenkins/jenkins
  restart: always
  ports:
   - 8082:8080
   - 50000:50000
  volumes:
   - jenkins:/var/jenkins_home
   - /var/run/docker.sock:/var/run/docker.sock
   - /usr/bin/docker:/usr/bin/docker 
     # - /usr/bin/:/usr/bin/
volumes:
  nexus:
  jenkins:
